void globale (void);
int NbArticle (void);
void fEnregNombre(int n);
void fVerif(int tab[],int i);
void fVerifReal(float tab[],int i);
void fVerifVal(int val);
void fCreerStock (void);
void fEtatStock(int ref[],int qt[],float prix[],int sds[],int n);
int fConsulterStock (int ref[],int qt[],float prix[],int sds[],int n);
void fAfficherStock (int ref[],int qt[],float prix[],int sds[],int n);
int fAppro (int ref[],int qt[],float prix[],int sds[],int n);
int fRecherche (int ref[],int n);
int fRecherche2 (int ref[],int n,int nref);
int fEnreg(int ref[],int qt[],float prix[],int sds[],int n);
int fSuppression (int ref[],int qt[],float prix[],int sds[],int n);
int fAjouter(int ref[],int qt[],float prix[],int sds[],int n);
int fModifier(int ref[],int qt[],float prix[],int sds[],int n);
