void globale (void);
void fCreerStock (void);
void fEtatStock(int ref[],int qt[],float prix[],int sds[],int n);
int fConsulterStock (int ref[],int qt[],float prix[],int sds[],int n);
void fAfficherStock (int ref[],int qt[],float prix[],int sds[],int n);
int NbArticle (void);
void fVerif(int tab[],int i);
void fVerifReal(float tab[],int i);
void fAppro (int ref[],int qt[],float prix[],int sds[],int n);
int fRecherche (int ref[],int n,int nref);
int fEnreg(int ref[],int qt[],float prix[],int sds[],int n);
int fSuppression (int ref[],int qt[],float prix[],int sds[],int n);
